### ISSUE TITLE
using one of our *counted* private repositories for no reason. move to your own public accounts or delete

### ISSUE THREAD

**Issue by YonatanRubin** [Spikes-2212-Programming-Guild/Skillz_thefluffyfaggots#1]
@saargb @Jelomite

**Comment by mtshrmn** [comment]
Can we close this issue? Its existence slightly annoys me.

**Comment by ThinkRedstone** [comment]
Well everyone, good job on dealing with this issue! It took us under 5 years, which I would say is a great success. 

On a personal note, I wish to say I never believed in any of you, and the fact we got here has left me baffled. Alas, even a broken clock is right twice a day.
